# Przykład fragmentu pliku .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # lub inna gałąź

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # Potrzebne do wdrożenia na GitHub Pages
      contents: read
      pages: write
      id-token: write
    environment: # Definiuje środowisko dla GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # lub inna wersja LTS

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build # Vite automatycznie użyje zmiennej środowiskowej
      env: # Przekazanie zmiennej repozytorium do procesu budowania
        VITE_CORRECT_PASSWORD: ${{ vars.VITE_CORRECT_PASSWORD }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist' # Ścieżka do zbudowanej aplikacji

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
